# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:              "Gauravjeet"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:title.html


# Navigation
nav:
  - name:           "GSoC16"
    href:           "/gsoc"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
