# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:              "Gauravjeet"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html


# Navigation
nav:
  - name:           "Project status"
    href:           "/status"
  - name:           "Proposal"
    href:           "/proposal"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
